### ISSUE TITLE
关于Person ReID 测试集上的指标疑问

### ISSUE THREAD

**Issue by zhustrong** [Astaxanthin/AdaSP#1]
老师您好，您的这个工作非常棒，低相似度正样本对的问题在工业界reid应用中也是非常重要的意义；
我在看论文实验对比部分时有一个疑问，想请教您一下：这篇论文中『表2』中的部分指标和其他论文对不上，例如在1501测试集下的指标是R1/mAP = 0.8+/0.7+ 而circle loss原论文表4的实验结果是0.9+/0.8+

**Comment by Astaxanthin** [comment]
> 老师您好，您的这个工作非常棒，低相似度正样本对的问题在工业界reid应用中也是非常重要的意义； 我在看论文实验对比部分时有一个疑问，想请教您一下：这篇论文中『表2』中的部分指标和其他论文对不上，例如在1501测试集下的指标是R1/mAP = 0.8+/0.7+ 而circle loss原论文表4的实验结果是0.9+/0.8+

感谢关注，circle loss原文中Person ReID的实验结果由learning with class-level labels（每类有weight vector，circle loss文章中公式2）得到，我们的文章中表2的结果均为learning with pair-wise labels（circle loss文章中的公式3），详细请参考config文件。

**Comment by zhustrong** [comment]
> > 老师您好，您的这个工作非常棒，低相似度正样本对的问题在工业界reid应用中也是非常重要的意义； 我在看论文实验对比部分时有一个疑问，想请教您一下：这篇论文中『表2』中的部分指标和其他论文对不上，例如在1501测试集下的指标是R1/mAP = 0.8+/0.7+ 而circle loss原论文表4的实验结果是0.9+/0.8+
> 
> 感谢关注，circle loss原文中Person ReID的实验结果由learning with class-level labels（每类有weight vector，circle loss文章中公式2）得到，我们的文章中表2的结果均为learning with pair-wise labels（circle loss文章中的公式3），详细请参考config文件。

明白了，谢谢您的回复~  目前开源的baseline基本都有用分类的loss，所以确实无法和其他论文的实验结果直接进行比较
