### ISSUE TITLE
model

### ISSUE THREAD

**Issue by zerobest** [Astaxanthin/AdaSP#2]
where is your model, please let me check check

**Comment by Astaxanthin** [comment]
Sorry we cannot provide model weights since they were stored on the server of the company where I interned, while I left my job before the code was releasing. I will consider retraining and releasing the checkpoints in the future but now I may not have time to do this.

**Comment by Astaxanthin** [comment]
> where is your model, please let me check check

Sorry we cannot provide model weights since they were stored on the server of the company where I interned, while I left my job before the code was releasing. I will consider retraining and releasing the checkpoints in the future but now I may not have time to do this.
