### ISSUE TITLE
Can you also release the checkpoints for evaluation?

### ISSUE THREAD

**Issue by chuong98** [Astaxanthin/AdaSP#3]
Hi, thanks for releasing the code. 
Would you mind releasing the checkpoints for quick evaluation?
Thank you,.

**Comment by ydm365** [comment]
Maybe the pretrained weight file is from [project IBN-Net](https://github.com/XingangPan/IBN-Net), because I find the pretrained weight file's name is exactly the same.

**Comment by Astaxanthin** [comment]
> Hi, thanks for releasing the code. Would you mind releasing the checkpoints for quick evaluation? Thank you,.

Sorry we cannot provide model weights since they were stored on the server of the company where I interned, while I left my job before the code was releasing. I will consider retraining and releasing the checkpoints in the future but now I may not have time to do this.
